<?php require_once('Connections/Ublq.php'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Mpfreebies - A Quality Streaming Tv - Radio - Movie Media Site</title>
<link href="/ublqstyle.css" rel="stylesheet" type="text/css" />
<link href="/includes/expand_script/ublq_expanded.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/includes/expand_script/ublq_expanded.js"></script>
<script type="text/javascript" src="/includes/player/t_r_m_g_player.js"></script>
<script type="text/javascript" src="/includes/disable_rightclick.js"></script>
</head>
<body onload="initShowHideDivs();">
<table width="1003" border="0" align="left" cellpadding="0" cellspacing="0">
  <tr>
    <td><?php include('includes/ublq_parts/startup_section.php'); ?>
<table width="1003" border="0" cellpadding="0" cellspacing="0" class="centertop">
  <tr>
    <td height="28"></td>
  </tr>
</table>
<table width="1003" border="0" cellpadding="0" cellspacing="0" class="center">
        <tr>
          <td valign="top"><table width="1002" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="46" height="148">&nbsp;</td>
                <td width="209" valign="top"><?php include('includes/ublq_parts/searchbox.php'); ?>
                   <?php include('includes/ublq_parts/tags.php'); ?>
                  <?php include('includes/ublq_parts/statistics.php'); ?>
                  <?php include('includes/ublq_parts/donate.php'); ?></td>
                <td width="10">&nbsp;</td>
                <td width="689" valign="top"><table width="687" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td width="631" height="28" class="headering_black">UBlq Terms &amp; Conditions  :</td>
                    <td width="59" valign="top"><table width="59" border="0" align="right" cellpadding="0" cellspacing="0" class="fold">
                      <tr>
                        <td height="23">&nbsp;</td>
                      </tr>
                    </table></td>
                  </tr>
                  
                </table>
                  <table width="682" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                      <td width="314" valign="top"><table width="600" border="0" cellpadding="0" cellspacing="0">
                        <tr>
                          <td width="703" height="480" valign="top" bgcolor="#FFFFFF"><p class="graytext">BY USING AND/OR VISITING THIS WEBSITE (collectively, including all Content available through the UBlq.com domain name, the &quot;UBlq Website&quot;, or &quot;Website&quot;), YOU SIGNIFY YOUR ASSENT TO THESE TERMS AND CONDITIONS. If you do not agree to any of these terms, then please do not use the UBlq Website. </p>
                            <p><span class="headering_Blue">1. UBlq Website</span><br />
                              <span class="text3">These Terms of Service apply to all users of the UBlq Website. The UBlq Website may contain links to third party websites. UBlq assumes no responsibility for, the content, privacy policies, or practices of any third party websites. In addition, UBlq will not and cannot censor or edit the content of any third-party site. By using the Website, you expressly relieve UBlq from any and all liability arising from your use of any third-party website. Accordingly, we encourage you to be aware when you leave the UBlq Website and to read the terms and conditions and privacy policy of each other website that you visit. </span><img src="/imagine/Scissor Cut.gif" alt="UBlq" width="682" height="20" /></p>
                            <p><span class="headering_Blue">2. Website Access</span><br />
                              <span class="text3">A. UBlq hereby grants you permission to use the Website, provided that: (i) your use of the Website as permitted is solely for your personal, noncommercial use; (ii) you will not copy or distribute any part of the Website in any medium without UBlq's prior written authorization; (iii) you will not alter or modify any part of the Website other than as may be reasonably necessary to use the Website for its intended purpose; and (iv) you will otherwise comply with the terms and conditions of these Terms of Service.</span></p>
                            <p class="text3">B. In order to access some features of the Website, you will have to create an account. You may never use another's account without permission. When creating your account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. You must notify UBlq immediately of any breach of security or unauthorized use of your account. Although UBlq will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of UBlq or others due to such unauthorized use. </p>
                            <p class="text3">C. You agree not to use or launch any automated system, including without limitation, &quot;robots,&quot; &quot;spiders,&quot; &quot;offline readers,&quot; etc., that accesses the Website in a manner that sends more request messages to the UBlq servers in a given period of time than a human can reasonably produce in the same period by using a convention on-line web browser. Notwithstanding the foregoing, UBlq grants the operators of public search engines permission to use spiders to copy materials from the site for the sole purpose of creating publicly available searchable indices of the materials, but not caches or archives of such materials. UBlq reserves the right to revoke these exceptions either generally or in specific cases. You agree not to collect or harvest any personally identifiable information, including account names, from the Website, nor to use the communication systems provided by the Website for any commercial solicitation purposes. You agree not to solicit, for commercial purposes, any users of the Website with respect to their User Submissions. <img src="/imagine/Scissor Cut.gif" alt="UBlq" width="682" height="20" /></p>
                            <p><span class="headering_Blue">3. Intellectual Property Rights</span><br />
                              <span class="text3">The content on the UBlq Website, except third party videostreams and User Submissions (as defined below), including without limitation, the text3, software, scripts, graphics, photos, sounds, music, videos, interactive features and the like (&quot;Content&quot;) and the trademarks, service marks and logos contained therein (&quot;Marks&quot;), are owned by or licensed to UBlq, subject to copyright and other intellectual property rights under The Netherlands and foreign laws and international conventions. Content on the Website is provided to you AS IS for your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. UBlq reserves all rights not expressly granted in and to the Website and the Content. You agree to not engage in the use, copying, or distribution of any of the Content other than expressly permitted herein, including any use, copying, ordistribution of User Submissions of third parties obtained through the Website for any commercial purposes. If you download or print a copy of the Content for personal use, you must retain all copyright and other proprietary notices contained therein. You agree not to circumvent, disable or otherwise interfere with security related features of the UBlq Website or features that prevent or restrict use or copying of any Content or enforce limitations on use of the UBlq Website or the Content therein.</span><img src="/imagine/Scissor Cut.gif" alt="UBlq" width="682" height="20" /></p>
                            <p><span class="headering_Blue">4. User Submissions</span><br />
                              <span class="text3">A. The UBlq Website may now or in the future permit the submission of videos or other communications submitted by you and other users (&quot;User Submissions&quot;) and the hosting, sharing, and/or publishing of such User Submissions. You understand that whether or not such User Submissions are published, UBlq does not guarantee any confidentiality with respect to any submissions.</span></p>
                            <p class="text3">B. You shall be solely responsible for your own User Submissions and the consequences of posting or publishing them. In connection with User Submissions, you affirm, represent, and/or warrant that: (i) you own or have the necessary licenses, rights, consents, and permissions to use and authorize UBlq to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Submissions to enable inclusion and use of the User Submissions in the manner contemplated by the Website and these Terms of Service; and (ii) you have the written consent, release, and/or permission of each and every identifiable individual person in the User Submission to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the User Submissions in the manner contemplated by the Website and these Terms of Service. For clarity, you retain all of your ownership rights in your User Submissions. However, by submitting the User Submissions to UBlq, you hereby grant UBlq a worldwide, non-exclusive, royalty-free, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the User Submissions in connection with the UBlq Website and UBlq's (and its successor's) business, including without limitation for promoting and redistributing part or all of the UBlq Website (and derivative works thereof) in any media formats and through any media channels. You also hereby grant each user of the UBlq Website a non-exclusive license to access your User Submissions through the Website, and to use, reproduce, distribute, prepare derivative works of, display and perform such User Submissions as permitted through the functionality of the Website and under these Terms of Service. The foregoing license granted by you terminates once you remove or delete a User Submission from the UBlq Website.</p>
                            <p class="text3">C. In connection with User Submissions, you further agree that you will not: (i) submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant UBlq all of the license rights granted herein; (ii) publish falsehoods or misrepresentations that could damage UBlq or any third party; (iii) submit material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate; (iv) post advertisements or solicitations of business: (v) impersonate another person. UBlq does not endorse any User Submission or any opinion, recommendation, or advice expressed therein, and UBlq expressly disclaims any and all liability in connection with User Submissions. UBlq does not permit copyright infringing activities and infringement of intellectual property rights on its Website, and UBlq will remove all Content and User Submissions if properly notified that such Content or User Submission infringes on another's intellectual property rights. UBlq reserves the right to remove Content and User Submissions without prior notice. UBlq will also terminate a User's access to its Website, if they are determined to be a repeat infringer. A repeat infringer is a User who has been notified of infringing activity more than twice and/or has had a User Submission removed from the Website more than twice. UBlq also reserves the right to decide whether Content or a User Submission is appropriate and complies with these Terms of Service for violations other than copyright infringement and violations of intellectual property law, such as, but not limited to, pornography, obscene or defamatory material, or excessive length. UBlq may remove such User Submissions and/or terminate a User's access for uploading such material in violation of these Terms of Service at any time, without prior notice and at its sole discretion. </p>
                            <p class="text3">D. In particular, if you are a copyright owner or an agent thereof and believe that any User Submission or other content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (&quot;DMCA&quot;) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail): </p>
                            <p class="text3">(i) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; </p>
                            <p class="text3">(ii) Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site; </p>
                            <p class="text3">(iii) Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;</p>
                            <p class="text3">(iv) Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail; </p>
                            <p class="text3">(v) A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and </p>
                            <p class="text3">(vi) A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. </p>
                            <p class="text3">E. You understand that when using the UBlq Website, you will be exposed to User Submissions from a variety of sources, and that UBlq is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such User Submissions. You further understand and acknowledge that you may be exposed to User Submissions that are inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against UBlq with respect thereto, and agree to indemnify and hold UBlq, its Owners/Operators, affiliates, and/or licensors, harmless to the fullest extent allowed by law regarding all matters related to your use of the site.</p>
                            <p class="text3">F. UBlq permits you to link to materials on the Website for personal, non-commercial purposes only. In addition, UBlq provides an &quot;Embeddable Player&quot; feature, which you may incorporate into your own personal, non-commercial websites for use in accessing the materials on the Website, provided that you include a prominent link back to the UBlq website on the pages containing the Embeddable Player. UBlq reserves the right to discontinue any aspect of the UBlq Website at any time.<img src="/imagine/Scissor Cut.gif" alt="UBlq" width="682" height="20" /></p>
                            <p><span class="headering_Blue">5. Warranty Disclaimer</span><br />
                              <span class="text3">YOU AGREE THAT YOUR USE OF THE UBlq WEBSITE SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, UBlq, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE WEBSITE AND YOUR USE THEREOF. UBlq MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THIS SITE'S CONTENT OR THE CONTENT OF ANY SITES LINKED TO THIS SITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR WEBSITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONSIN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE UBlq WEBSITE. UBlq DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE UBlq WEBSITE OR ANY HYPERLINKED WEBSITE OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND UBlq WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</span><img src="/imagine/Scissor Cut.gif" alt="UBlq" width="682" height="20" /></p>
                            <p><span class="headering_Blue">6. Limitation of Liability</span><br />
                              <span class="text3">IN NO EVENT SHALL UBlq, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR WEBSITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE UBlq WEBSITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER ORNOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION. </span></p>
                            <p class="text3">YOU SPECIFICALLY ACKNOWLEDGE THAT UBlq SHALL NOT BE LIABLE FOR USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU. </p>
                            <p class="text3">The Website is controlled and offered by UBlq from its facilities in The Netherlands. UBlq makes no representations that the UBlq Website is appropriate or available for use in other locations. Those who access or use the UBlq Website from other jurisdictions do so at their own volition and are responsible for compliance with local law. <img src="/imagine/Scissor Cut.gif" alt="UBlq" width="682" height="20" /></p>
                            <p><span class="headering_Blue">7. Indemnity</span><br />
                              <span class="text3">You agree to defend, indemnify and hold harmless UBlq, its parent corporation, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the UBlq Website; (ii) your violation of any term of these Terms of Service; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that one of your User Submissions caused damage to a third party. This defense and indemnification obligation will survive these Terms of Service and your use of the UBlq Website. </span><img src="/imagine/Scissor Cut.gif" alt="UBlq" width="682" height="20" /></p>
                            <p><span class="headering_Blue">8. Ability to Accept Terms of Service</span><br />
                              <span class="text3">You affirm that you are either more than 18 years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. In any case, you affirm that you are over the age of 13, as the UBlq Website is not intended for children under 13. If you are under 13 years of age, then please do not use the UBlq Website—there are lots of other great web sites for you. Talk to your parents about what sites are appropriate for you.</span><img src="/imagine/Scissor Cut.gif" alt="UBlq" width="682" height="20" /></p>
                            <p><span class="headering_Blue">9. Assignment</span><br />
                              <span class="text3">These Terms of Use, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by UBlq without restriction. </span><img src="/imagine/Scissor Cut.gif" alt="UBlq" width="682" height="20" /></p>
                            <p><span class="headering_Blue">10. General</span><br />
                              <span class="text3">You agree that: (i) the UBlq Website shall be deemed solely based in The Netherlands; and (ii) the UBlq Website shall be deemed a passive website that does not give rise to personal jurisdiction over UBlq, either specific or general, in jurisdictions other than California. These Terms of Service shall be governed by the internal substantive laws of The Netherlands, without respect to its conflict of laws principles. Any claim or dispute between you and UBlq that arises in whole or in part from the UBlq Website shall be decided exclusively by a court of competent jurisdiction located in The Netherlands. These Terms of Use and any other legal notices published by UBlq on the Website, shall constitute the entire agreement between you and UBlq concerning the UBlq Website. If any provision of these Terms of Use is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Service, which shall remain in full force and effect. No waiver of any term of this these Terms of Service shall be deemed a further or continuing waiver of such term or any other term, and UBlq's failure to assert any right or provision under these Terms of Use shall not constitute a waiver of such right or provision. UBlq reserves the right to amend these Terms of Use at any time and without notice, and it is your responsibility to review these Terms of Use for any changes. Your use of the UBlq Website following any amendment of these Terms of Use will signify your assent to and acceptance of its revised terms. YOU AND UBlq AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE UBlq WEBSITE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</span><br />
                            </p>                            </td>
                        </tr>
                      </table></td>
                  </tr>
                    <tr>
                      <td valign="top"><img src="/imagine/Scissor Cut.gif" width="682" height="20" /></td>
                    </tr>
                  </table>                  
                  </td>
                <td width="48">&nbsp;</td>
              </tr>
          </table></td>
        </tr>
      </table>
      <table width="1003" border="0" cellpadding="0" cellspacing="0" class="centerbot">
        <tr>
          <td height="7"></td>
        </tr>
      </table>
      <table width="1003" border="0" cellpadding="0" cellspacing="0" class="bot">
        <tr>
          <td valign="top"><table width="200" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="8"></td>
              </tr>
            </table>
              <table width="911" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                  <td width="605" valign="top"><?php include('includes/ublq_parts/about_ublq.php'); ?></td>
                <td width="302" valign="top"><?php include('includes/ublq_parts/ads_bottom.php'); ?></td>
                </tr>
            </table>
      <table width="200" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                  <td height="6"></td>
                </tr>
            </table></td>
        </tr>
      </table>
      <?php include('includes/ublq_parts/bottom_links.php'); ?></td>
  </tr>
</table>
</body>
</html>
